# Generated by Django 3.2.6 on 2022-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание товара', max_length=1000, null=True, verbose_name='Описание товара'),
        ),
    ]
